ssh:
  children:
    docker:

docker:
  children:
    docker_managers:
    docker_workers:

docker_managers:
  hosts:
    DOCKER-00[1:3]:

docker_workers:
  hosts:
    DOCKER-00[4:6]:
